// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Sources/InstantSearchCore/Telemetry/telemetry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum TelemetryComponentType: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unknown // = 0
  case hitsSearcher // = 1
  case facetSearcher // = 2
  case multiSearcher // = 3
  case answersSearcher // = 4
  case filterState // = 5

  /// Dynamic Facets
  case dynamicFacets // = 6

  /// Hierarchical Menu
  case hierarchicalFacets // = 7

  /// Refinement List
  case facetList // = 8

  /// Clear Filters
  case filterClear // = 9

  /// Filter List (Facet)
  case facetFilterList // = 10

  /// Filter List (Numeric)
  case numericFilterList // = 11

  /// Filter List (Tag)
  case tagFilterList // = 12

  /// Filter Toggle
  case filterToggle // = 13

  /// Filter Numeric Comparison
  case numberFilter // = 14

  /// Filter Numeric Range
  case numberRangeFilter // = 15

  /// Current Filters
  case currentFilters // = 16

  /// Hits
  case hits // = 17

  /// Loading
  case loading // = 18

  /// Stats
  case stats // = 19

  /// SearchBox
  case searchBox // = 20

  /// QueryRuleCustomData
  case queryRuleCustomData // = 21

  /// RelevantSort
  case relevantSort // = 22

  /// SortBy
  case sortBy // = 23

  /// Related items
  case relatedItems // = 24

  /// Filter Map
  case filterMap // = 25

  /// Multi Hits
  case multiHits // = 26
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .hitsSearcher
    case 2: self = .facetSearcher
    case 3: self = .multiSearcher
    case 4: self = .answersSearcher
    case 5: self = .filterState
    case 6: self = .dynamicFacets
    case 7: self = .hierarchicalFacets
    case 8: self = .facetList
    case 9: self = .filterClear
    case 10: self = .facetFilterList
    case 11: self = .numericFilterList
    case 12: self = .tagFilterList
    case 13: self = .filterToggle
    case 14: self = .numberFilter
    case 15: self = .numberRangeFilter
    case 16: self = .currentFilters
    case 17: self = .hits
    case 18: self = .loading
    case 19: self = .stats
    case 20: self = .searchBox
    case 21: self = .queryRuleCustomData
    case 22: self = .relevantSort
    case 23: self = .sortBy
    case 24: self = .relatedItems
    case 25: self = .filterMap
    case 26: self = .multiHits
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .hitsSearcher: return 1
    case .facetSearcher: return 2
    case .multiSearcher: return 3
    case .answersSearcher: return 4
    case .filterState: return 5
    case .dynamicFacets: return 6
    case .hierarchicalFacets: return 7
    case .facetList: return 8
    case .filterClear: return 9
    case .facetFilterList: return 10
    case .numericFilterList: return 11
    case .tagFilterList: return 12
    case .filterToggle: return 13
    case .numberFilter: return 14
    case .numberRangeFilter: return 15
    case .currentFilters: return 16
    case .hits: return 17
    case .loading: return 18
    case .stats: return 19
    case .searchBox: return 20
    case .queryRuleCustomData: return 21
    case .relevantSort: return 22
    case .sortBy: return 23
    case .relatedItems: return 24
    case .filterMap: return 25
    case .multiHits: return 26
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension TelemetryComponentType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [TelemetryComponentType] = [
    .unknown,
    .hitsSearcher,
    .facetSearcher,
    .multiSearcher,
    .answersSearcher,
    .filterState,
    .dynamicFacets,
    .hierarchicalFacets,
    .facetList,
    .filterClear,
    .facetFilterList,
    .numericFilterList,
    .tagFilterList,
    .filterToggle,
    .numberFilter,
    .numberRangeFilter,
    .currentFilters,
    .hits,
    .loading,
    .stats,
    .searchBox,
    .queryRuleCustomData,
    .relevantSort,
    .sortBy,
    .relatedItems,
    .filterMap,
    .multiHits,
  ]
}

#endif  // swift(>=4.2)

enum TelemetryComponentParams: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case undefined // = 0
  case apiKey // = 1
  case appID // = 2
  case attribute // = 3
  case bounds // = 4
  case clearMode // = 5
  case client // = 6
  case facets // = 7
  case filter // = 8
  case filterGroupForAttribute // = 9
  case filterGroupIds // = 10
  case groupName // = 11
  case hierarchicalAttributes // = 12
  case indexName // = 13
  case infiniteScrolling // = 14
  case item // = 15
  case items // = 16
  case `operator` // = 17
  case orderedFacets // = 18
  case priority // = 19
  case range // = 20
  case searchTriggeringMode // = 21
  case searcher // = 22
  case isSelected // = 23
  case selectionMode // = 24
  case selectionModeForAttribute // = 25
  case selections // = 26
  case separator // = 27
  case showItemsOnEmptyQuery // = 28
  case isDisjunctiveFacetingEnabled // = 29
  case isLoading // = 30
  case mode // = 31
  case number // = 32
  case persistentSelection // = 33
  case searchMode // = 34
  case strategy // = 35
  case groupIds // = 36
  case filters // = 37
  case numericOperator // = 38
  case selected // = 39
  case filterStateParameter // = 40
  case hitsSearcherParameter // = 41
  case facetSearcherParameter // = 42
  case UNRECOGNIZED(Int)

  init() {
    self = .undefined
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .undefined
    case 1: self = .apiKey
    case 2: self = .appID
    case 3: self = .attribute
    case 4: self = .bounds
    case 5: self = .clearMode
    case 6: self = .client
    case 7: self = .facets
    case 8: self = .filter
    case 9: self = .filterGroupForAttribute
    case 10: self = .filterGroupIds
    case 11: self = .groupName
    case 12: self = .hierarchicalAttributes
    case 13: self = .indexName
    case 14: self = .infiniteScrolling
    case 15: self = .item
    case 16: self = .items
    case 17: self = .operator
    case 18: self = .orderedFacets
    case 19: self = .priority
    case 20: self = .range
    case 21: self = .searchTriggeringMode
    case 22: self = .searcher
    case 23: self = .isSelected
    case 24: self = .selectionMode
    case 25: self = .selectionModeForAttribute
    case 26: self = .selections
    case 27: self = .separator
    case 28: self = .showItemsOnEmptyQuery
    case 29: self = .isDisjunctiveFacetingEnabled
    case 30: self = .isLoading
    case 31: self = .mode
    case 32: self = .number
    case 33: self = .persistentSelection
    case 34: self = .searchMode
    case 35: self = .strategy
    case 36: self = .groupIds
    case 37: self = .filters
    case 38: self = .numericOperator
    case 39: self = .selected
    case 40: self = .filterStateParameter
    case 41: self = .hitsSearcherParameter
    case 42: self = .facetSearcherParameter
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .undefined: return 0
    case .apiKey: return 1
    case .appID: return 2
    case .attribute: return 3
    case .bounds: return 4
    case .clearMode: return 5
    case .client: return 6
    case .facets: return 7
    case .filter: return 8
    case .filterGroupForAttribute: return 9
    case .filterGroupIds: return 10
    case .groupName: return 11
    case .hierarchicalAttributes: return 12
    case .indexName: return 13
    case .infiniteScrolling: return 14
    case .item: return 15
    case .items: return 16
    case .operator: return 17
    case .orderedFacets: return 18
    case .priority: return 19
    case .range: return 20
    case .searchTriggeringMode: return 21
    case .searcher: return 22
    case .isSelected: return 23
    case .selectionMode: return 24
    case .selectionModeForAttribute: return 25
    case .selections: return 26
    case .separator: return 27
    case .showItemsOnEmptyQuery: return 28
    case .isDisjunctiveFacetingEnabled: return 29
    case .isLoading: return 30
    case .mode: return 31
    case .number: return 32
    case .persistentSelection: return 33
    case .searchMode: return 34
    case .strategy: return 35
    case .groupIds: return 36
    case .filters: return 37
    case .numericOperator: return 38
    case .selected: return 39
    case .filterStateParameter: return 40
    case .hitsSearcherParameter: return 41
    case .facetSearcherParameter: return 42
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension TelemetryComponentParams: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [TelemetryComponentParams] = [
    .undefined,
    .apiKey,
    .appID,
    .attribute,
    .bounds,
    .clearMode,
    .client,
    .facets,
    .filter,
    .filterGroupForAttribute,
    .filterGroupIds,
    .groupName,
    .hierarchicalAttributes,
    .indexName,
    .infiniteScrolling,
    .item,
    .items,
    .operator,
    .orderedFacets,
    .priority,
    .range,
    .searchTriggeringMode,
    .searcher,
    .isSelected,
    .selectionMode,
    .selectionModeForAttribute,
    .selections,
    .separator,
    .showItemsOnEmptyQuery,
    .isDisjunctiveFacetingEnabled,
    .isLoading,
    .mode,
    .number,
    .persistentSelection,
    .searchMode,
    .strategy,
    .groupIds,
    .filters,
    .numericOperator,
    .selected,
    .filterStateParameter,
    .hitsSearcherParameter,
    .facetSearcherParameter,
  ]
}

#endif  // swift(>=4.2)

struct TelemetryComponent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: TelemetryComponentType = .unknown

  var parameters: [TelemetryComponentParams] = []

  var isConnector: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct TelemetrySchema {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var components: [TelemetryComponent] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TelemetryComponentType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN"),
    1: .same(proto: "hitsSearcher"),
    2: .same(proto: "facetSearcher"),
    3: .same(proto: "multiSearcher"),
    4: .same(proto: "answersSearcher"),
    5: .same(proto: "filterState"),
    6: .same(proto: "dynamicFacets"),
    7: .same(proto: "hierarchicalFacets"),
    8: .same(proto: "facetList"),
    9: .same(proto: "filterClear"),
    10: .same(proto: "facetFilterList"),
    11: .same(proto: "numericFilterList"),
    12: .same(proto: "tagFilterList"),
    13: .same(proto: "filterToggle"),
    14: .same(proto: "numberFilter"),
    15: .same(proto: "numberRangeFilter"),
    16: .same(proto: "currentFilters"),
    17: .same(proto: "hits"),
    18: .same(proto: "loading"),
    19: .same(proto: "stats"),
    20: .same(proto: "searchBox"),
    21: .same(proto: "queryRuleCustomData"),
    22: .same(proto: "relevantSort"),
    23: .same(proto: "sortBy"),
    24: .same(proto: "relatedItems"),
    25: .same(proto: "filterMap"),
    26: .same(proto: "multiHits"),
  ]
}

extension TelemetryComponentParams: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "undefined"),
    1: .same(proto: "apiKey"),
    2: .same(proto: "appID"),
    3: .same(proto: "attribute"),
    4: .same(proto: "bounds"),
    5: .same(proto: "clearMode"),
    6: .same(proto: "client"),
    7: .same(proto: "facets"),
    8: .same(proto: "filter"),
    9: .same(proto: "filterGroupForAttribute"),
    10: .same(proto: "filterGroupIDs"),
    11: .same(proto: "groupName"),
    12: .same(proto: "hierarchicalAttributes"),
    13: .same(proto: "indexName"),
    14: .same(proto: "infiniteScrolling"),
    15: .same(proto: "item"),
    16: .same(proto: "items"),
    17: .same(proto: "operator"),
    18: .same(proto: "orderedFacets"),
    19: .same(proto: "priority"),
    20: .same(proto: "range"),
    21: .same(proto: "searchTriggeringMode"),
    22: .same(proto: "searcher"),
    23: .same(proto: "isSelected"),
    24: .same(proto: "selectionMode"),
    25: .same(proto: "selectionModeForAttribute"),
    26: .same(proto: "selections"),
    27: .same(proto: "separator"),
    28: .same(proto: "showItemsOnEmptyQuery"),
    29: .same(proto: "isDisjunctiveFacetingEnabled"),
    30: .same(proto: "isLoading"),
    31: .same(proto: "mode"),
    32: .same(proto: "number"),
    33: .same(proto: "persistentSelection"),
    34: .same(proto: "searchMode"),
    35: .same(proto: "strategy"),
    36: .same(proto: "groupIDs"),
    37: .same(proto: "filters"),
    38: .same(proto: "numericOperator"),
    39: .same(proto: "selected"),
    40: .same(proto: "filterStateParameter"),
    41: .same(proto: "hitsSearcherParameter"),
    42: .same(proto: "facetSearcherParameter"),
  ]
}

extension TelemetryComponent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TelemetryComponent"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    600: .same(proto: "type"),
    601: .same(proto: "parameters"),
    602: .same(proto: "isConnector"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 600: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 601: try { try decoder.decodeRepeatedEnumField(value: &self.parameters) }()
      case 602: try { try decoder.decodeSingularBoolField(value: &self.isConnector) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 600)
    }
    if !self.parameters.isEmpty {
      try visitor.visitPackedEnumField(value: self.parameters, fieldNumber: 601)
    }
    if self.isConnector != false {
      try visitor.visitSingularBoolField(value: self.isConnector, fieldNumber: 602)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TelemetryComponent, rhs: TelemetryComponent) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.parameters != rhs.parameters {return false}
    if lhs.isConnector != rhs.isConnector {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TelemetrySchema: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TelemetrySchema"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    700: .same(proto: "components"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 700: try { try decoder.decodeRepeatedMessageField(value: &self.components) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.components.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.components, fieldNumber: 700)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TelemetrySchema, rhs: TelemetrySchema) -> Bool {
    if lhs.components != rhs.components {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
