excluded:
 - .build
 - ./Tests
 - ./Examples
# implicitly
line_length: 300
identifier_name:
  excluded:
    - on
    - or
    - id
function_parameter_count:
  warning: 8
  error: 10
  ignores_default_parameters: true
function_body_length:
  warning: 60
  error: 100
disabled_rules:
  - todo
  - implicit_getter
nesting:
 type_level: 2
