# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstantSearchDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'InstantSearch-iOS', :path => '/Users/guydaher/Developer/Algolia/instantsearch-ios'
pod 'InstantSearch-Core-Swift', :path => '/Users/guydaher/Developer/Algolia/instantsearch-core-swift'

end
