name: Carthage
on: [pull_request]
jobs:
  check:
    runs-on: macos-15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.0.app/Contents/Developer'
      - name: Initialize Cartfile
        run: |
          tee Cartfile <<<"github \"algolia/instantsearch-ios\" \"${{ github.head_ref }}\""
          carthage update --no-build
          carthage build --use-xcframeworks --platform ios
