name: Carthage
on: [pull_request]
jobs:
  check:
    runs-on: macos-13
    steps:
     - name: Select Xcode version
       run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
     - name: Initialize Cartfile
       run: |
        tee Cartfile <<<"github \"algolia/instantsearch-ios\" \"${{ github.head_ref }}\""
        carthage update --no-build
        sh ./Carthage/Checkouts/instantsearch-ios/carthage-prebuild
        carthage build --use-xcframeworks --platform ios
